name: jump_recipe
channels:
  - bioconda
  - conda-forge
dependencies:
  - numpy=1.24.4
  - pandas=1.5.3
  - pyarrow=11.0.0
  - scikit-learn=1.3.2
  - snakemake-minimal=7.32.4
  - harmonypy=0.0.9
  - tqdm=4.66.2
  - awscli=2.15.53
  - pip=23.3.1
  - jq=1.7.1
  - pip:
      - git+https://github.com/cytomining/copairs.git@v0.4.1
